name: Update
on:
  schedule:
    # Every 30 minutes
    - cron: '*/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_BUILD_HOOK }}
